package com.utbm.lo54.formation_app.core.entities;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "formation", uniqueConstraints = @UniqueConstraint(columnNames = "EMAIL"))
public class Client implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private CourseSession courseSession;
	private String lastname;
	private String firstname;
	private String address;
	private String phone;
	private String email;

	public Client() {
	}

	
	
	public Client(CourseSession courseSession, String lastname, String firstname, String address, String phone,
			String email) {
		this.courseSession = courseSession;
		this.lastname = lastname;
		this.firstname = firstname;
		this.address = address;
		this.phone = phone;
		this.email = email;
	}
	
//	public Client(int id, CourseSession courseSession, String lastname, String firstname, String address, String phone,
//			String email) {
//		this.id = id;
//		this.courseSession = courseSession;
//		this.lastname = lastname;
//		this.firstname = firstname;
//		this.address = address;
//		this.phone = phone;
//		this.email = email;
//	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "COURSE_SESSION_ID", nullable = false)
	public CourseSession getCourseSession() {
		return this.courseSession;
	}

	public void setCourseSession(CourseSession courseSession) {
		this.courseSession = courseSession;
	}

	@Column(name = "LASTNAME", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "FIRSTNAME", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "ADDRESS", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PHONE", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "EMAIL", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "Client [id=" + id + ", courseSession=" + courseSession + ", lastname=" + lastname + ", firstname="
				+ firstname + ", address=" + address + ", phone=" + phone + ", email=" + email + "]";
	}

}
